### ISSUE TITLE
Setting a custom directory location - where are the models stored?

### ISSUE THREAD

**Issue by kwikiel** [simonw/llm#118]
I've installed the library and played with the vicuna model but I wonder where the model is stored? Seems like here:
https://llm.datasette.io/en/stable/setup.html#setting-a-custom-directory-location

but when I've tried to see it's contents it only has gpt4all_models.json file

**Comment by dbready** [comment]
After some poking around, it looks like the llm-gpt4all package relies upon the gpt4all functionality to handle most of the downloading pieces. On Linux, it puts the models in `~/.config/gpt4all`

**Comment by kwikiel** [comment]
I've found that on Mac it's on  ~/.cache/gpt4all

https://github.com/nomic-ai/gpt4all/blob/main/gpt4all-bindings/python/gpt4all/gpt4all.py
