### ISSUE TITLE
Mention templates implementation in System prompt documentation

### ISSUE THREAD

**Issue by oaustegard** [simonw/llm#131]
Would be good to make mention of templates also having the option of including system prompts (as per #44) in the documentation at https://llm.datasette.io/en/stable/usage.html#system-prompts

Perhaps an edge case but is it feasible to want two different templates, one for the system and one for the user prompt?

**Comment by simonw** [comment]
I did think about the potential for loading more than one template at one point. The idea would be to support this:

```bash
cat code.py | llm -t glados -t explain-code
```
This would load the `glados` template and the `explain-code` template and combine them in some way.

I wasn't sure how best to combine them though. Maybe just concatenating the prompts from both together (in the order they were specified) would make sense.

I'll move this to a separate issue.

**Comment by simonw** [comment]
Thanks for the suggestion, that change is now live in the docs here: https://llm.datasette.io/en/latest/usage.html#system-prompts
