### ISSUE TITLE
Installing via homebrew: "Error: LLModel.prompt_model() got an unexpected keyword argument 'max_tokens'"

### ISSUE THREAD

**Issue by bensheldon** [simonw/llm#134]
When following the directions in [this toot](https://ruby.social/@simon@simonwillison.net/110775467728500558) (:heart:) I ran into this error:

```bash
❯ llm -m 'ggml-vicuna-7b-1' 'ten fun names for a pet pelican'
Error: LLModel.prompt_model() got an unexpected keyword argument 'max_tokens'
```

This is my list of plugins:

```
❯ llm plugins
[
  {
    "name": "llm.default_plugins.openai_models",
    "hooks": [
      "register_commands",
      "register_models"
    ]
  },
  {
    "name": "llm-gpt4all",
    "hooks": [
      "register_models"
    ],
    "version": "0.1.1"
  }
]
```

**Comment by eblume** [comment]
The GPT4All project no longer lists this model, so I can't reproduce it.

In the mean time, this works, and is relatively quick to test (~5GB downloaded): `llm -m 'ggml-replit-code-v1-3b' 'ten fun names for a pet pelican'`

(Although in this specific case, the replit model is optimized for coding - and this one is quite small - so it produces some insane garbage.)

If you're still having this issue can you please confirm it happens with other models currently in their codebase?

**Comment by bensheldon** [comment]
@eblume thank you for the help! That works 👍🏻 

```
❯ llm -m 'ggml-replit-code-v1-3b' 'ten fun names for a pet pelican'
.

I'm not sure how to do this, but I think it would be easy enough with the help of some Python code:ggml_metal_free: deallocating
```

And the response matches the expectations you set 😆
