### ISSUE TITLE
Can't troubleshoot proxy gateway OpenAI endpoints

### ISSUE THREAD

**Issue by klauern** [simonw/llm#139]
I have an internal proxy gateway that uses it's own API keys, but it is supposed to be equivalent to the `https://api.openai.com/*` endpoints.  However, when i try to run the `llm` tool with it, I get errors and I don't have a way to debug it:

Here's the `extra-openai-models.yaml`
```
- model_id: mine
  aliases: ["mine"]
  model_name: gpt-4-32k
  api_base: "https://mylocation-gateway.place.com"
```

when I run it I get this:

```sh
 llm -m mine --key mine
hello # Ctrl-D
Error: Invalid response object from API: '404 page not found\n' (HTTP response code was 404)
```

**Comment by klauern** [comment]
Related, I was hoping to suss out the issue with the logs db, but #138 is blocking me

**Comment by klauern** [comment]
Did some more noodling, and I found that if I set `api_key_name` in `extra-openai-models.yaml` it will work, but I still have to pass the `--key` flag to the CLI:

```
llm -m mine --key mine "hello" --log
Hello! How can I assist you today?
```

**Comment by klauern** [comment]
Similarly, it's also easier to just set the `OPENAI_API_KEY` and `OPENAI_API_BASE` environment variables than it is to use the `extra-openai-models.yaml` at all.

**Comment by simonw** [comment]
I just added a mechanism that should help debug these:
- #286 

See https://llm.datasette.io/en/latest/contributing.html#debugging-tricks
