### ISSUE TITLE
Remove partial model download

### ISSUE THREAD

**Issue by fingerguns83** [simonw/llm#142]
Where are the models downloaded to? My internet dropped when downloading one of the ggml models and rather than re-downloading on the next run, it's just running with the partial download. I've tried uninstalling llm and the gpt4all plugin, checked the "Application Support/io.datasette" directory, checked the homebrew cellar.

**Comment by daaain** [comment]
The model for me was downloaded to `~/Library/Application Support/io.datasette.llm/llama-cpp/models/llama-2-7b-chat.ggmlv3.q8_0.bin`

**Comment by mattflo** [comment]
This happened to me too. There must be state somewhere else. When I list models my failed one shows as installed, but it is not in that directory.

**Comment by mattflo** [comment]
I found where the gpt4all llama-2-7b model was partially downloaded on macOS. Deleting it caused the download to start again.

`rm ~/.cache/gpt4all/llama-2-7b-chat.ggmlv3.q4_0.bin`

**Comment by fingerguns83** [comment]
> I found where the gpt4all llama-2-7b model was partially downloaded on macOS. Deleting it caused the download to start again.
> 
> `rm ~/.cache/gpt4all/llama-2-7b-chat.ggmlv3.q4_0.bin`

You absolute legend. There should definitely be a 'force re-install/re-download' option, though.

**Comment by fingerguns83** [comment]
> I found where the gpt4all llama-2-7b model was partially downloaded on macOS. Deleting it caused the download to start again.
> 
> `rm ~/.cache/gpt4all/llama-2-7b-chat.ggmlv3.q4_0.bin`

You absolute legend. There should definitely be a 'force re-install/re-download' option, though.
