### ISSUE TITLE
Piping in input and providing an argument prompt should combine them

### ISSUE THREAD

**Issue by simonw** [simonw/llm#153]
This caught me out this morning: https://gist.github.com/simonw/ff20b534439497ecaa068001621c7205

I tried this:
```bash
./combined-release-notes.sh simonw/llm | \
  llm 'how do I install it' -m mlc-chat-Llama-2-7b-chat-hf-q4f16_1
```
And got back a response just for the prompt "how do I install it" without the piped in content being processed by the model at all.

This confused me: https://twitter.com/simonw/status/1690377023414521856

**Comment by simonw** [comment]
The natural way to handle this would be to append the `how do I install it` to the end of the prompt, since intuitively this feature would be used for things like asking questions about what came before it.

I used this as a workaround:

```
llm "$(/tmp/combined-release-notes.sh simonw/llm) how do I install it" \
  -m mlc-chat-Llama-2-7b-chat-hf-q4f16_1
```

**Comment by simonw** [comment]
Relevant code: https://github.com/simonw/llm/blob/4db949bae8f7dba48b853090baed61183a5df0ef/llm/cli.py#L125-L135

**Comment by simonw** [comment]
So the new logic should be:

- `prompt` is the prompt that came from the positional argument to `llm "prompt here"`
- Use `not sys.stdin.isatty()` to detect if there is content waiting on standard input
- If there IS, read that and turn prompt into `{content-from-stdin} {prompt}`
- Otherwise only do the thing where we block and wait for input to `stdin` if no template and no `--save` and no prompt provided

**Comment by tomviner** [comment]
This will really be appreciated for models which don't have a system prompt, like claude.

Currently my workaround is bash/zsh command groups, i.e. `{}`:

```bash
curl -s https://docs.anthropic.com/claude/reference/selecting-a-model \
  | trafilatura --output-format txt \
  | { echo "Find any typos in this text"; cat } \
  | llm -m claude
```

The nice features of this approach:
- easy to add either prefix or suffix stdin, or both
- automatic newline separation, so model won't get confused where pieces of data start and end 

(`trafilatura` gives slightly cleaner output than `strip-tags` btw)

**Comment by simonw** [comment]
Got it working:
```bash
cat pytest.ini | llm 'explain this file like an angry pelican who wants fish'
```

> Listen up, you human! This is a pytest configuration file! And don't you dare think you can ignore me, because I've got something important to tell you.
> 
> You see that line that says "ignore::pydantic.main.PydanticDeprecatedSince20"? Yeah, that's my way of saying, "Hey, stupid, stop ignoring the fact that Pydantic has been deprecated since version 20!"
> 
> I mean, seriously, how hard is it to update your code when there's a deprecation warning? Pydantic has clearly put in the effort to let you know that they've made changes and improvements in version 20, and you're just ignoring it? Unbelievable!
> 
> I'm like an angry pelican here, flapping my wings and squawking at you to pay attention! I want you to acknowledge that Pydantic has evolved and that you need to adapt your code accordingly. No more taking the easy way out and pretending like everything is fine.
> 
> So, get your act together, human! Listen to the warnings, update your code, and give me the fish I deserve!
>

**Comment by simonw** [comment]
This doesn't work:
```bash
llm 'explain like an angry pelican' --save pelican
cat pytest.ini | llm -t pelican
```
It ignores the stdin and just explains random things as a pelican.

But this does work:
```bash
llm '$input. explain like an angry pelican' --save pelican
cat pytest.ini | llm -t pelican
```
So I think that's OK - that's already a documented feature.

**Comment by simonw** [comment]
Updated documentation: https://llm.datasette.io/en/latest/usage.html#executing-a-prompt-against-openai

**Comment by AlexanderYastrebov** [comment]
Hello, thank you for the great tool.

It would be nice and versatile to support appending stdin to the prompt argument (i.e. `{prompt} {content-from-stdin}`).
To make this work in backwards compatible way and to avoid adding new flags it can be implemented similar to https://github.com/kharvd/gpt-cli:
1. allow multiple prompt positional arguments, join them with space before executing
2. support special argument value `-` that, when present, is replaced by stdin content

This way one may use the tool like:
```sh
echo "What is the diameter of Earth in kilometers?" | llm "Please answer the following:" - "Provide answer as the number only."
```

If that makes sense I can create a PR.
