### ISSUE TITLE
`api_key_name` isn't used in `extra-openai-models.yaml` if `OPENAI_API_KEY` env var is set

### ISSUE THREAD

**Issue by itsderek23** [simonw/llm#158]
If I add an openai-compatible model to `extra-openai-models.yaml` and specify an `api_key_name`, the CLI does not appear to use the key value. Instead, it appears to use the `openai` key.

Example key file:

```json
{
  "// Note": "This file stores secret API credentials. Do not share!",
  "openai": "sk-redacted",
  "opstower": "redacted"
}
```

Example CLI command (inspecting server logs shows that the `openai` key value was passed):

```shell
llm -m opstower 'how many ec2 instances'
```

This works:

```shell
llm -m opstower 'how many ec2 instances' --key opstower
```

Orignally mentioned by @klauern in https://github.com/simonw/llm/issues/139#issuecomment-1664257078_

This is on version 0.7.

**Comment by itsderek23** [comment]
I believe this happens if the env var `OPENAI_API_KEY` is set. If I unset this, it works. 

Looking at `get_key`, the `env_var` is checked prior to `default_key`.

**Comment by simonw** [comment]
Relevant code: https://github.com/simonw/llm/blob/a4f55e9987f32d4a46c4baaca46b757a16010f06/llm/__init__.py#L97-L105

**Comment by simonw** [comment]
I don't like those variable names, and that function needs proper documentation. It's confusing to look at.

**Comment by simonw** [comment]
The main place that is called is: https://github.com/simonw/llm/blob/a4f55e9987f32d4a46c4baaca46b757a16010f06/llm/models.py#L209-L234

**Comment by simonw** [comment]
The main place the `get_key()` function is called is here: https://github.com/simonw/llm/blob/a4f55e9987f32d4a46c4baaca46b757a16010f06/llm/cli.py#L211-L213

**Comment by itsderek23** [comment]
I'll try to do a PR for this next week. Thanks for the pointers.

**Comment by simonw** [comment]
I wrote this:
```diff
diff --git a/llm/models.py b/llm/models.py
index 10006bf..4cfd1e9 100644
--- a/llm/models.py
+++ b/llm/models.py
@@ -217,15 +217,24 @@ class Model(ABC):
         pass
 
     def get_key(self):
+        from llm import get_key
+
         if self.needs_key is None:
+            # This model doesn't use an API key
             return None
+
         if self.key is not None:
+            # Someone already set model.key='...'
             return self.key
-        if self.key_env_var is not None:
-            key = os.environ.get(self.key_env_var)
-            if key:
-                return key
 
+        # Attempt to load a key using llm.get_key()
+        key = get_key(
+            explicit_key=None, key_alias=self.needs_key, env_var=self.key_env_var
+        )
+        if key:
+            return key
+
+        # Show a useful error message
         message = "No key found - add one using 'llm keys set {}'".format(
             self.needs_key
         )
```
But I need to come up with a robust test plan for ensuring it does what it needs to do.

**Comment by simonw** [comment]
I can test this more easily using the OpenRouter support I added in:
- #165

**Comment by simonw** [comment]
Managed to replicate this bug:
```
$ llm -m claude 'say hi and your name'                 
 Hello, my name is Claude. It's nice to meet you!
$ OPENAI_API_KEY=x llm -m claude 'say hi and your name'
Error: Invalid credentials
```

**Comment by simonw** [comment]
This was a deliberate design decision: https://github.com/simonw/llm/blob/341dbce2d57b4178bd3bcfacf586c627bd6a76bd/llm/__init__.py#L114-L118

I'm trying to remember why.

**Comment by simonw** [comment]
I'm going to change that decision.

If you want to use the key from your environment variable instead, you can do this:

```bash
llm "my prompt" --key $OPENAI_API_KEY
```

**Comment by simonw** [comment]
Updated documentation: https://llm.datasette.io/en/latest/setup.html#keys-in-environment-variables

**Comment by itsderek23** [comment]
Thank you @simonw !

**Comment by cmungall** [comment]
This is more of a note for myself if I end up searching the docs again.

When using `extra-openai-models.yaml`, it seems natural to assume you can do this:

```yaml
- model_name: lbl/llama-3
  model_id: lbl/llama-3
  api_base: "https://api.cborg.lbl.gov"
  api_key_name: CBORG_API_KEY
```

and it will pick up `CBORG_API_KEY` from the env. In fact this doesn't happen - it needs to be done using `llm keys`, or on the command line as specified above.

I prefer the former, so I usually give a more conventional key name:

```yaml
- model_name: lbl/llama-3
  model_id: lbl/llama-3
  api_base: "https://api.cborg.lbl.gov"
  api_key_name: cborg
```

and manage this using

```bash
llm keys set cborg
```
