### ISSUE TITLE
sqlite_utils.db.AlterError: No such column: log.id

### ISSUE THREAD

**Issue by hydrosquall** [simonw/llm#164]
Hi,

I recently upgraded sqlite-utils from 3.33 to 3.35 in the environment that has `llm installed`

I'm getting the error

> sqlite_utils.db.AlterError: No such column: log.id

![image](https://github.com/simonw/llm/assets/9020979/2a2b6444-a776-4dd7-af45-b00efd3183ba)

I'm assuming there is a database used for logging that might have had the wrong schema so I tried running `llm logs status`, and hit a similar error.

![image](https://github.com/simonw/llm/assets/9020979/c505d1a7-ce62-4982-9556-788fe4a7c54d)

I tried deleting the database file and the regenerating a new log using the llm mlc package, but the original error persists.

Any ideas for what I could do to fix the logging capability?

## Metadata

- M1 Mac
- llm version 0.7
- Python 3.9.9
- sqlite-utils 3.35

Here's the schema of the table that does exist, using 

    datasette "$(llm logs path)"

<img width="499" alt="image" src="https://github.com/simonw/llm/assets/9020979/a81923ef-16ad-4e2c-997b-fae4807e4263">

**Comment by hydrosquall** [comment]
Upon closer inspection, this may be a duplicate of https://github.com/simonw/llm/issues/162 .

**Comment by kevinschaul** [comment]
I think you're right @hydrosquall. By chance are you able to see if #163 fixes it for you?

**Comment by simonw** [comment]
I'm having trouble replicating this issue. Could you confirm your SQLite version too, along with the compile options?

Could you try running this and report back the results:

```bash
python -c '
import sqlite3
import sys
conn = sqlite3.connect(":memory:")
print("Python version:", sys.version)
print("SQLite version:", conn.execute("select sqlite_version()").fetchone()[0])
print("SQLite compile options\n  " + "\n  ".join(r[0] for r in conn.execute("pragma compile_options").fetchall()))
'
``

**Comment by simonw** [comment]
Turned that recipe into a TIL :https://til.simonwillison.net/sqlite/python-sqlite-environment

**Comment by simonw** [comment]
Also try this:
```python
python -c '
from llm.migrations import migrate
from sqlite_utils import Database
db = Database(memory=True)
migrate(db)
print(db.schema)
'
```
That purely runs the migrations against an in-memory database, and should show if you get that error or not for that simplest possible case.

**Comment by simonw** [comment]
I think this is fixed:
- https://github.com/simonw/llm/issues/162#issuecomment-1685096919

**Comment by hydrosquall** [comment]
Confirmed that upgrading to `0.7.1` and deleting the old database together have successfully fixed the issue. Thanks for the fast response and documenting how to debug similar issues for next time!

![image](https://github.com/simonw/llm/assets/9020979/ec4dbd10-7f1b-43f6-849b-38e955beba23)
