### ISSUE TITLE
What is the hardware requirement running llm models?

### ISSUE THREAD

**Issue by ipstone** [simonw/llm#197]
Nice tool and great talk! I am led there through the talk, which was really nice!

Playing with llm, I have successfully run the models such as:
`llm -m  GPT4All-13B-snoozy 'Where is the captial of France?'`

However, running on a centOS 7 workstation, downloading the model worked fine, but model can not be initiated. I am wondering what is the hardware requirement to run llm models? my CPU is Intel(R) Xeon(R) Gold 5222 CPU @ 3.80GHz, GPU is Quadro P4000

I know the GPU driver isn't properly configured, might that be the cause of problem (update: just configured the GPU properly, but still can not initiate the models ... on the other hand, mac M1/intel works both fine) ?

**Comment by eblume** [comment]
Can you share the error message you're receiving?

[According to the GPT4All project](https://docs.gpt4all.io/gpt4all_faq.html#what-are-the-system-requirements), the requirements are that your CPU must support the AVX or AVX2 extension, which you can test with:

```bash
grep -o 'avx\|avx2' /proc/cpuinfo | sort | uniq
```

If this prints 'avx' or 'avx2' (or both), you should be supported, provided you also have enough RAM for the model. I'm not sure of a reliable way to determine if you have sufficient RAM to run an inference on a model, but I would assume you'll need more than 8GB of RAM to run that model. 16GB should be sufficient. Less will probably work.

Finally you can also try running a much smaller model to see if inference can even happen, or if there's some other issue. Of course small models tend to have worse output, so this is mostly just for testing.

**Comment by eblume** [comment]
Actually, I just noticed, the output of `llm models` includes this info:

```bash
❯ llm models
...
gpt4all: GPT4All-13B-snoozy - Snoozy, 7.58GB download, needs 16GB RAM
...
```

This information is gathered via the GPT4All python API, where they get that from I'm not sure.

**Comment by ipstone** [comment]
Thanks!  Testing the CPU:
```
grep -o 'avx\|avx2' /proc/cpuinfo | sort | uniq
avx
avx2
```

so there should be no issue on this workstation. The workstation has 64GB RAM, which also should not be a problem.
But even when I try to use a smaller model, I have the following error:
```
llm -m orca-mini-7b 'What is the capital of France?'
100%|██████████████████████████████████████████████████████████████████████| 3.79G/3.79G [00:38<00:00, 98.9MiB/s]
Error: Unable to instantiate model
```

**Comment by daonb** [comment]
@ipstone been over a year, have you solved this? If so, please close this issue

**Comment by ipstone** [comment]
this issue was resolved - somehow I forgot the specifics, perhaps it worked after system reboot or nvidia driver update. Thanks, closing it now.
