### ISSUE TITLE
embed-multi from a .csv file

### ISSUE THREAD

**Issue by rsbohn** [simonw/llm#249]
The documentation says use this:

    llm embed-multi items -i mydata.csv

but when I run that I get:

    Error: No such option: -i

Seems to work if I drop the `-i`. Not sure if the documentation or the implementation needs to be updated.

I'm running *llm, version 0.10a0*

**Comment by simonw** [comment]
Looks like that's a documentation bug - thanks for spotting it:

https://github.com/simonw/llm/blob/3c888082d4ec7236f9d1184ddac20c35a6f10c28/llm/cli.py#L1092-L1098

**Comment by simonw** [comment]
Updated documentation: https://llm.datasette.io/en/stable/embeddings/cli.html#embedding-data-from-a-csv-tsv-or-json-file
