### ISSUE TITLE
Unable to find sentence-transformers.json on first install

### ISSUE THREAD

**Issue by litso** [simonw/llm#252]
Hello I used venv to install so i'm note sure if that caused the problem, but i'm getting the following error trying to register the all-MiniLM-L6-v2 embeddings model.

```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/litso/Library/Application Support/io.datasette.llm/sentence-transformers.json'
```

Here is how i installed everything:

```
 > python3 --version                                                                                                                                           Fri Sep  8 17:02:40 2023
Python 3.11.5
> python3 -m venv llm
> . llm/bin/activate.fish
> pip install llm
> llm install llm-sentence-transformers
> llm sentence-transformers register all-MiniLM-L6-v2
💣
```

Should i give up trying to use venv? Thanks in advance!

**Comment by simonw** [comment]
Looks like that was this bug, now fixed:
- https://github.com/simonw/llm-sentence-transformers/issues/9

Running this should upgrade to the working version:
```bash
llm install -U llm-sentence-transformers
```
