### ISSUE TITLE
DOC: Inconsistency in README regarding LLAMA parameters - are they 7b or 13b?

### ISSUE THREAD

**Issue by corneliusroemer** [simonw/llm#304]
There seems to be inconsistency in whether the llama model has 7b or 13b parameters.

The README states:

> Then download the 15GB Llama 2 13B model like this:
> ```
> llm mlc download-model Llama-2-7b-chat --alias llama2
> ```
> And run a prompt through it:
> 
> llm -m llama2 'difference between a llama and an alpaca'
> You can also start a chat session with the model using the llm chat command:
> 
> ```
> llm chat -m llama2
> Chatting with mlc-chat-Llama-2-13b-chat-hf-q4f16_1
> Type 'exit' or 'quit' to exit
> Type '!multi' to enter multiple lines, then '!end' to finish
> ```

The install command seems to be for the 7b model. But the docs talk about 13b.

**Comment by simonw** [comment]
Thanks!
