### ISSUE TITLE
Add support for gpt-4-turbo

### ISSUE THREAD

**Issue by simonw** [simonw/llm#323]
Announced at OpenAI DevDay today - ~3x cheaper than GPT-4, and has a 128,000 token limit.

**Comment by simonw** [comment]
Not working yet (I guessed the model name):
```bash
llm --model gpt-4-turbo 'hi'                                 
```
```
Error: The model `gpt-4-turbo` does not exist
```

**Comment by simonw** [comment]
Now working in this branch: https://github.com/simonw/llm/compare/gpt-4-turbo

**Comment by simonw** [comment]
Oh it's `gpt-4-1106-preview` according to https://openai.com/blog/new-models-and-developer-products-announced-at-devday

Not working yet though:

```
$ llm -m gpt-4-turbo 'hi'
Error: The model `gpt-4-1106-preview` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.
```

**Comment by fourseven** [comment]
Appreciate the work you've done with LLM, it's a very useful tool. I followed the [Adding more OpenAI Models](https://llm.datasette.io/en/stable/other-models.html#adding-more-openai-models) instructions for the new model to set it up, and wanted to post this for others until it's officially released/supported.

For what it's worth, my account also doesn't yet have access, the following results in `Error: The model `GPT4 Turbo` does not exist`

`llm -m gpt-4-1106-preview "Generate 5 names for a pet mice that are puns"`

```yaml
# $(llm logs path)/extra-openai-models.yaml

- model_id: gpt-4-1106-preview
  model_name: GPT-4 Turbo
  aliases: ['gpt-4-turbo', '4-turbo', '4t']

```

**Comment by simonw** [comment]
Demo to summarize comments on https://news.ycombinator.com/item?id=38166420

```
curl -s "https://hn.algolia.com/api/v1/items/38166420" | \
  jq -r 'recurse(.children[]) | .author + ": " + .text' | \
  llm -m gpt-4-turbo 'Summarize the themes of the opinions expressed here,
  including direct quotes in quote markers (with author attribution) for each theme.
  Fix HTML entities. Output markdown. Go long.'
```
Output: https://gist.github.com/simonw/d50c8634320d339bd88f0ef17dea0a03

**Comment by simonw** [comment]
> Appreciate the work you've done with LLM, it's a very useful tool. I followed the [Adding more OpenAI Models](https://llm.datasette.io/en/stable/other-models.html#adding-more-openai-models) instructions for the new model to set it up, and wanted to post this for others until it's officially released/supported.

Nice! I am glad that feature worked as intended.

**Comment by cmungall** [comment]
For anyone following the instructions here: https://llm.datasette.io/en/stable/other-models.html#adding-more-openai-models

I had to add both `model_id` and `model_name` e.g.

```yaml
- model_name: gpt-4-1106-preview
  model_id: gpt-4 turbo preview
  aliases: ["4-turbo", "gpt-4-turbo"]
```

**Comment by shvechikov** [comment]
What about adding an explicit support for [JSON mode](https://platform.openai.com/docs/guides/text-generation/json-mode) introduced in GPT-4 Turbo?
```
openai.Completion.create(
    ...
    response_format={ "type": "json_object" }
)
```
