### ISSUE TITLE
gpt-3.5-turbo-16k Support

### ISSUE THREAD

**Issue by benjamin-kirkbride** [simonw/llm#37]
Would love to see gpt-3.5-turbo-16k support, along with the 0613 models.

See: https://community.openai.com/t/gpt-3-5-turbo-0613-function-calling-16k-context-window-and-lower-prices/263263

**Comment by benjamin-kirkbride** [comment]
Actually, the base models will be getting the 0613 treatment soon, so probably not worth doing that.

> On June 27th, the stable gpt-3.5-turbo will be automatically upgraded to this new version.

**Comment by benjamin-kirkbride** [comment]
I see this is going to be covered by https://github.com/simonw/llm/issues/17, but depending on how long it will take to be done, would be cool to have this out sooner :)

**Comment by cw** [comment]
Is this not already in place? See https://til.simonwillison.net/llms/larger-context-openai-models-llm

**Comment by benjamin-kirkbride** [comment]
Oh okay awesome, didn't realize. Would be awesome for llm to automatically bump to the 16k model when necessary, but maybe that's out of scope :)
