### ISSUE TITLE
llm chat - readline problems still present

### ISSUE THREAD

**Issue by kevinburke** [simonw/llm#376]
When I open `llm chat`, I expect that using the left and right arrow keys will navigate the cursor but instead I get nasty ANSI codes printed to the screen. 

```
$ llm chat
Chatting with gpt-4
Type 'exit' or 'quit' to exit
Type '!multi' to enter multiple lines, then '!end' to finish
> foo bar ^[[D^[[D^[[D^[[D^[[D
```

I am using the latest version of llm, commit 5cc8efe98f49b3aaeddf0c05b7827efda411a916 (the readline support commit), installed by checking out this commit locally, starting a virtualenv and running "python setup.py install", then running e.g. `./venv/bin/llm`. 

I also verified that my Python version has readline support:

```
$ python
Python 3.10.13 (main, Nov  7 2023, 20:58:26) [Clang 15.0.0 (clang-1500.0.40.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import readline
>>> print(readline.__doc__)
Importing this module enables command line editing using GNU readline.
```

Let me know what else I can do to help troubleshoot.

**Comment by kugurerdem** [comment]
I had the same experience. Running ``rlwrap llm chat`` resolved the issue for me when I wanted to chat through llm. However, it's a bit unfortunate that this great program has issues with readline.

Personally, I liked this program a lot and would like to see this problem addressed and solved.

**Comment by simonw** [comment]
Working with ChatGPT: https://chat.openai.com/share/b5e1a34e-e365-4455-8d17-265ef80101c0 I found this magic incantation which seems to do the right thing:

```python
    readline.parse_and_bind("\\e[D: backward-char")
    readline.parse_and_bind("\\e[C: forward-char")
```
Weirdly obscure!

**Comment by simonw** [comment]
Demo of that fix:

![readline](https://github.com/simonw/llm/assets/9599/65c790e4-397a-4dab-8610-2ccaa1559b28)
