### ISSUE TITLE
[FR] Add configuration option for changing an LLMs URL

### ISSUE THREAD

**Issue by bmoe872** [simonw/llm#382]
# Why
The way we've implemented our usage of OpenAI's API is to go through a gateway. This enables our devops and sys admin teams to investigate requests going through and ensure that we're not potentially sending off any secure data that people shouldn't be sending. It also enables us the ability to have a "single source" for all the API calls being made. 

It would be wonderful to be able to configure an existing LLM to point at a different endpoint URL.

**Comment by vividfog** [comment]
As far as I can tell from this request, this is already possible and has been for a while: https://llm.datasette.io/en/stable/other-models.html

Here's the format I use in `extra-openai-models.yaml` and it works.

Per model:

```
- model_id: gw-gpt-3.5-turbo
  model_name: gpt-3.5-turbo
  api_base: "https://my-gateway.url/v1/"
  headers:
    team-name: "team-1"
    team-key: "abcdefg"
```

This assumes that there is a model with a name "gpt-3.5-turbo" available behind the gateway and there are some custom HTTP headers that the gateway requires from callers.

I would call this model (for example) like this:

`llm chat -m my-gpt-3.5-turbo`

That'd initiate an OpenAI chat with https://my-gateway.url/v1/ and the model it serves when gpt-3.5-turbo is called.

Some gateways don't have streaming support, and only produce the output as one blob of text at the end. If that's the case, add `--no-stream` as a command line option.

Models configured this way can also be called via the `llm` Python API.

Another use case for extra-openai-models is to configure llama.cpp to serve Mistral or some other strong open-license model, and tell `llm` about it, just like above. Llama.cpp can be served as an OpenAI endpoint by using the `llama-cpp-python` library, or via Ollama.ai as a local model host and LiteLLM as an OpenAI proxy/converter for it. Those are in Github too. With an all-local pipeline, nothing can leak.

**Comment by cmungall** [comment]
Thanks for the tip about how to bridge llm and litellm in this way, it would be great if the docs made this more obvious!

**Comment by bmoe872** [comment]
Thank you @vividfog for this! I didn't realize that was possible. I'm not sure how we'd get the `team-key` in this example in place though without also checking in the key for the file. I'll close this for now though since the original ask is already doable! Thank you!
