### ISSUE TITLE
Error about needing to install mlc_chat first, but it is installed

### ISSUE THREAD

**Issue by vegarsti** [simonw/llm#403]
I've ran the commands in the [Installing a model that runs on your own machine](https://github.com/simonw/llm?tab=readme-ov-file#installing-a-model-that-runs-on-your-own-machine) to install `llm-mlc` and `mlc-chat-nightly` but when I run

```
llm -m llama2 'difference between a llama and an alpaca'
```

I get the "Error: You must install mlc_chat first." message.

Ditto if I do `llm chat -m llama2`:

```
Chatting with mlc-chat-Llama-2-13b-chat-hf-q4f16_1
Type 'exit' or 'quit' to exit
Type '!multi' to enter multiple lines, then '!end' to finish
> hello
Error: You must install mlc_chat first.
```

My `llm --version is 0.12`.

What am I doing wrong? 😬

**Comment by simonw** [comment]
This is really odd. I'm not sure what went wrong here, but I've updated the README to recommend `llm-gpt4all` as the first plugin to try since it's less likely to go wrong (simpler installation process).

**Comment by vegarsti** [comment]
Perfect, now I have local models! Thanks so much!
