### ISSUE TITLE
Image model support?

### ISSUE THREAD

**Issue by angerman** [simonw/llm#428]
Is there a way/plan to support image generators? E.g. Dall-E, and similar?
Same for TTS?

**Comment by simonw** [comment]
No plans at all for image generation - that feels out of scope for the LLM tool to me, but could definitely happen in other similar tools.

Likewise for TTS - I'm more interested in solving that with pipes to other tools. I have one of those already - https://github.com/simonw/ospeak - which can run like this:

    llm 'tell me something cool about pelicans' | ospeak -v fable

I am however going to add support for image inputs, see:
- https://github.com/simonw/llm/issues/331
