### ISSUE TITLE
`llm logs` option for returning just the response from the most recent prompt

### ISSUE THREAD

**Issue by simonw** [simonw/llm#431]
Right now` llm logs list` (and its default alias `llm logs`) returns Markdown with both the prompt and the response. Add `--json` and it returns JSON for that.

I found myself wanting to repeat just the last response so I could pipe it to `ospeak`.

I did this:

```bash
llm logs -c --json | jq '.[0].response' -r | ospeak
```
But I'd rather have an option to get `llm logs` to output that directly.

I think `llm logs -r/--response` would be good - it outputs just the response text from the last returned log line, as raw text ready to be piped to other tools.

Using `-r` implies `llm logs list -c` as well, because you are looking for the most recent item.

**Comment by simonw** [comment]
Documentation: https://github.com/simonw/llm/blob/fb63c92cd27053700daa5420a0d1ad8fdfb718bd/docs/logging.md#viewing-the-logs

**Comment by simonw** [comment]
This now works:
```bash
llm 'tell me something cool about pelicans'
llm logs -r | ospeak -o /tmp/pelicans.mp3
```
https://github.com/simonw/llm/assets/9599/f636ff0a-c6af-4b16-a7cd-b120151ae3a8

**Comment by ddgond** [comment]
I was about to submit a PR to add in a `llm logs last` command, but thankfully found this PR while looking for a commit message format. Cheers, and thanks for all your work on this!
