### ISSUE TITLE
Updating plugins

### ISSUE THREAD

**Issue by noamross** [simonw/llm#452]
Hello! Thank you for making such an excellent tool. I was wondering what the expected approach is to updating plugins.  I believe that they can be updated by just re-installing, so I could script this with:

```bash
llm plugins | jq -r '.[] | .name' | xargs -I{} llm install {}
```

Or is this/should it be built-in?

**Comment by pointlessone** [comment]
You're close, `llm install` needs `-U`/`--upgrade` argument to actually upgrade an installed plugin.
