### ISSUE TITLE
Asynchronous API support

### ISSUE THREAD

**Issue by czue** [simonw/llm#487]
Have you considered adding support for Asychronous APIs for the models that support it? It would make deploying `llm` as part of a web application easier and more scalable.

Would you accept contributions that tried to add this functionality?

**Comment by simonw** [comment]
Yes, I absolutely want to do this.

I need it myself for Datasette plugins such as https://github.com/datasette/datasette-extract and https://github.com/datasette/datasette-enrichments-gpt

**Comment by simonw** [comment]
Dupe of:
- #507
