### ISSUE TITLE
Support for extra-index-url

### ISSUE THREAD

**Issue by keviddles** [simonw/llm#586]
I am trying to install a custom plugin hosted on a private Gitlab instance.

[`pip` supports `--extra-index-url`](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-extra-index-url) to specify additional package indexes.

`llm` does not appear to support this option:

```
Usage: llm install [OPTIONS] [PACKAGES]...
Try 'llm install --help' for help.

Error: No such option: --extra-index-url
```

Although, in the docs I see:

> Use the llm install command (a thin wrapper around pip install) to install plugins in the correct environment

But I'm not sure if the option is meant to be omitted for other reasons I'm not privy to.

**Comment by simonw** [comment]
There's a workaround for the moment: you can install the `llm-python` plugin:

```bash
llm install llm-python
```
And then run `pip` like this:
```bash
llm python -m pip install ... --extra-index-url ...
```
Let me know if that works. I'm not sure if it's worth adding more options to `llm install` when this workaround exists.

**Comment by keviddles** [comment]
That works great! Agreed, no need to add options with this workaround.

[Might be worth throwing a link to this comment in the docs](https://llm.datasette.io/en/stable/plugins/installing-plugins.html#installing-plugins) for future folks.
