### ISSUE TITLE
Attachment feature with OpenAi compatible model don't recognize capabilities

### ISSUE THREAD

**Issue by ibeex** [simonw/llm#593]
I added custom gpt-4o azure model through `extra-openai-models.yaml` and Api proxy config is 
```
- model_id: 4o-azure
  model_name: azure-gpt4o
  api_base: "http://10.41.9.156:4000/"
  api_key_name: azure-gpt4o
  ```
  then command returns
  ```
  "describe this image" \
        -a IMG_20240908_161441.jpg
Error: This model does not support attachments, but some were provided
```
Is there option to extra models that indicate model supports attachments or any other function?

**Comment by simonw** [comment]
This is the same issue as:
- #602
