### ISSUE TITLE
Consider using XDG_DATA_HOME directory instead of .llm

### ISSUE THREAD

**Issue by llimllib** [simonw/llm#7]
The [XDG base directory spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) has a directory that would be perfect for this tool's database: `~/.local/share/llm`.

There are two big advantages to using `XDG_DATA_HOME` instead of `~/.llm`:

- Users can easily configure the directory to use by setting `XDG_DATA_HOME`
- Limits the explosion of dot directories in the home directory

[here's how I implement it in my similar tool](https://github.com/llimllib/gpt-bash-cli/blob/587b790d90b671876a8d9d08848c2370e87dd84b/gpt#L109), for reference - use `XDG_DATA_HOME` if present, otherwise default to `~/.local/share/<app_name>`

**Comment by simonw** [comment]
Yeah I should definitely do something like this. There are Python libraries out there for "put things in the right hidden folder for the OS" but I've not yet figured out which one is most useful for this kind of thing.

**Comment by nealmcb** [comment]
I agree.

Related to #13 - probably want a different place to store the API key also (now in `$HOME/.openai-api-key.txt`)

**Comment by simonw** [comment]
I was going to use https://github.com/ActiveState/appdirs but it says it has been deprecated in favour of https://pypi.org/project/platformdirs/ - which looks healthy: https://github.com/platformdirs/platformdirs

**Comment by simonw** [comment]
Should I have the tool perform a one-off migration when you upgrade it, to move `~/.llm/log.db` to the new location?

I think not - instead, I'll have `llm init-db` take an optional argument for starting the database by copying an existing one, then mention that upgrade path in the release notes.

**Comment by simonw** [comment]
This is done.
